/**
 * Generated by scripts/gen-redirects.mjs — do not edit by hand.
 *
 * Every URL WordPress serves today either exists at the same path in this build
 * or appears here. Regenerate after running scripts/wp-inventory.mjs.
 *
 * 36 one-to-one rules plus 5 platform rules.
 * `redirects` below is the readable record; `platformRoutes` is what actually
 * ships — see the note above it.
 */
export interface Redirect {
  from: string;
  to: string;
  status: 301 | 302;
}

export const redirects: Redirect[] = [
  /* post moved under /blog/ */
  { from: "/shopify-sidekick-integration/", to: "/blog/shopify-sidekick-integration/", status: 301 },
  /* post moved under /blog/ */
  { from: "/shopify-faq-builder-app/", to: "/blog/shopify-faq-builder-app/", status: 301 },
  /* post moved under /blog/ */
  { from: "/faq-schema-and-product-schema-shopify-ai-search/", to: "/blog/faq-schema-and-product-schema-shopify-ai-search/", status: 301 },
  /* post moved under /blog/ */
  { from: "/shopify-ai-chatbot-storefaq-guide/", to: "/blog/shopify-ai-chatbot-storefaq-guide/", status: 301 },
  /* post moved under /blog/ */
  { from: "/search-behavior-keywords-to-question-based-intent/", to: "/blog/search-behavior-keywords-to-question-based-intent/", status: 301 },
  /* post moved under /blog/ */
  { from: "/migrating-faqs-in-shopify-how-to-export-import-faqs/", to: "/blog/migrating-faqs-in-shopify-how-to-export-import-faqs/", status: 301 },
  /* post moved under /blog/ */
  { from: "/ai-faq-app-for-shopify/", to: "/blog/ai-faq-app-for-shopify/", status: 301 },
  /* post moved under /blog/ */
  { from: "/message-shortcuts-in-storefaq/", to: "/blog/message-shortcuts-in-storefaq/", status: 301 },
  /* post moved under /blog/ */
  { from: "/faq-page-vs-qapage-vs-product-schema-shopify/", to: "/blog/faq-page-vs-qapage-vs-product-schema-shopify/", status: 301 },
  /* post moved under /blog/ */
  { from: "/shopify-instant-answer-app-to-answer-customer-queries/", to: "/blog/shopify-instant-answer-app-to-answer-customer-queries/", status: 301 },
  /* post moved under /blog/ */
  { from: "/how-to-create-a-shopify-faq-page-using-storefaq/", to: "/blog/how-to-create-a-shopify-faq-page-using-storefaq/", status: 301 },
  /* post moved under /blog/ */
  { from: "/shopify-ai-faq-builder-create-product-faqs-with-ai/", to: "/blog/shopify-ai-faq-builder-create-product-faqs-with-ai/", status: 301 },
  /* post moved under /blog/ */
  { from: "/best-shopify-faq-apps/", to: "/blog/best-shopify-faq-apps/", status: 301 },
  /* post moved under /blog/ */
  { from: "/how-shopify-faq-schema-helps-boost-aeo-and-geo/", to: "/blog/how-shopify-faq-schema-helps-boost-aeo-and-geo/", status: 301 },
  /* post moved under /blog/ */
  { from: "/multilingual-faq-why-does-your-shopify-store-need-it/", to: "/blog/multilingual-faq-why-does-your-shopify-store-need-it/", status: 301 },
  /* post moved under /blog/ */
  { from: "/top-reasons-add-shopify-faq-page/", to: "/blog/top-reasons-add-shopify-faq-page/", status: 301 },
  /* category has no posts */
  { from: "/category/uncategorized/", to: "/blog/", status: 301 },
  /* BetterLinks */
  { from: "/BFCM-2025-Faq-Audit", to: "https://storeware.io/storefaq-talk-with-expert/", status: 302 },
  /* BetterLinks */
  { from: "/download/sample-faq", to: "https://storefaq.io/wp-content/uploads/2024/12/faq_sample.csv", status: 302 },
  /* BetterLinks */
  { from: "/go/betterdocs-for-shopify", to: "https://apps.shopify.com/betterdocs-knowledgebase", status: 302 },
  /* BetterLinks */
  { from: "/go/easyflow", to: "https://apps.shopify.com/product-options-4", status: 302 },
  /* BetterLinks */
  { from: "/go/get-started", to: "https://apps.shopify.com/storefaq", status: 302 },
  /* BetterLinks */
  { from: "/go/partners-page", to: "https://apps.shopify.com/storefaq?utm_campaign=partnerpage&utm_medium=partnership&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { from: "/go/social-media-shoutout", to: "https://apps.shopify.com/storefaq?utm_campaign=socialpost&utm_medium=partnership&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-AltMaster", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=AltMaster", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-fether", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=fether", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-iCart-Cart-Drawer", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=iCartCartDrawer", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-makeprosimp", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=MakeProSimp", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-parcelwill", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=ParcelWILL", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-PHMultiCarrier", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=PHMultiCarrier", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-weglot", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=WEGLOT", status: 302 },
  /* BetterLinks */
  { from: "/go/storefaq-with-xFlow", to: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { from: "/go/storeseo", to: "https://apps.shopify.com/storeseo", status: 302 },
  /* BetterLinks */
  { from: "/go/tech-partner-landing-page", to: "https://apps.shopify.com/storefaq?utm_campaign=techpartnerlanding&utm_medium=partnership&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { from: "/go/trustsync", to: "https://apps.shopify.com/customer-review-app", status: 302 },
  /* BetterLinks */
  { from: "/Schedule-a-Call-Now", to: "https://storeware.io/storefaq-talk-with-expert/", status: 302 },
];

/**
 * What actually ships. Merged into .vercel/output/config.json by the
 * integration in astro.config, PREPENDED so these run before the trailing-slash
 * normaliser.
 *
 * Astro's own `redirects` is deliberately not used: with trailingSlash
 * 'always' its adapter emits slash-less patterns and orders them after the 308
 * normaliser, so a real old URL — which always ends in a slash — matches
 * nothing and 404s. Every pattern here accepts the slash either way.
 */
export interface PlatformRoute {
  src: string;
  dest?: string;
  status: number;
}

export const platformRoutes: PlatformRoute[] = [
  /* post moved under /blog/ */
  { src: "^/shopify-sidekick-integration/?$", dest: "/blog/shopify-sidekick-integration/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/shopify-faq-builder-app/?$", dest: "/blog/shopify-faq-builder-app/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/faq-schema-and-product-schema-shopify-ai-search/?$", dest: "/blog/faq-schema-and-product-schema-shopify-ai-search/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/shopify-ai-chatbot-storefaq-guide/?$", dest: "/blog/shopify-ai-chatbot-storefaq-guide/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/search-behavior-keywords-to-question-based-intent/?$", dest: "/blog/search-behavior-keywords-to-question-based-intent/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/migrating-faqs-in-shopify-how-to-export-import-faqs/?$", dest: "/blog/migrating-faqs-in-shopify-how-to-export-import-faqs/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/ai-faq-app-for-shopify/?$", dest: "/blog/ai-faq-app-for-shopify/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/message-shortcuts-in-storefaq/?$", dest: "/blog/message-shortcuts-in-storefaq/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/faq-page-vs-qapage-vs-product-schema-shopify/?$", dest: "/blog/faq-page-vs-qapage-vs-product-schema-shopify/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/shopify-instant-answer-app-to-answer-customer-queries/?$", dest: "/blog/shopify-instant-answer-app-to-answer-customer-queries/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/how-to-create-a-shopify-faq-page-using-storefaq/?$", dest: "/blog/how-to-create-a-shopify-faq-page-using-storefaq/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/shopify-ai-faq-builder-create-product-faqs-with-ai/?$", dest: "/blog/shopify-ai-faq-builder-create-product-faqs-with-ai/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/best-shopify-faq-apps/?$", dest: "/blog/best-shopify-faq-apps/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/how-shopify-faq-schema-helps-boost-aeo-and-geo/?$", dest: "/blog/how-shopify-faq-schema-helps-boost-aeo-and-geo/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/multilingual-faq-why-does-your-shopify-store-need-it/?$", dest: "/blog/multilingual-faq-why-does-your-shopify-store-need-it/", status: 301 },
  /* post moved under /blog/ */
  { src: "^/top-reasons-add-shopify-faq-page/?$", dest: "/blog/top-reasons-add-shopify-faq-page/", status: 301 },
  /* category has no posts */
  { src: "^/category/uncategorized/?$", dest: "/blog/", status: 301 },
  /* BetterLinks */
  { src: "^/BFCM-2025-Faq-Audit/?$", dest: "https://storeware.io/storefaq-talk-with-expert/", status: 302 },
  /* BetterLinks */
  { src: "^/download/sample-faq/?$", dest: "https://storefaq.io/wp-content/uploads/2024/12/faq_sample.csv", status: 302 },
  /* BetterLinks */
  { src: "^/go/betterdocs-for-shopify/?$", dest: "https://apps.shopify.com/betterdocs-knowledgebase", status: 302 },
  /* BetterLinks */
  { src: "^/go/easyflow/?$", dest: "https://apps.shopify.com/product-options-4", status: 302 },
  /* BetterLinks */
  { src: "^/go/get-started/?$", dest: "https://apps.shopify.com/storefaq", status: 302 },
  /* BetterLinks */
  { src: "^/go/partners-page/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnerpage&utm_medium=partnership&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { src: "^/go/social-media-shoutout/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=socialpost&utm_medium=partnership&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-AltMaster/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=AltMaster", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-fether/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=fether", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-iCart-Cart-Drawer/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=iCartCartDrawer", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-makeprosimp/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=MakeProSimp", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-parcelwill/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=ParcelWILL", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-PHMultiCarrier/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=PHMultiCarrier", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-weglot/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=WEGLOT", status: 302 },
  /* BetterLinks */
  { src: "^/go/storefaq-with-xFlow/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=partnership&utm_medium=app&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { src: "^/go/storeseo/?$", dest: "https://apps.shopify.com/storeseo", status: 302 },
  /* BetterLinks */
  { src: "^/go/tech-partner-landing-page/?$", dest: "https://apps.shopify.com/storefaq?utm_campaign=techpartnerlanding&utm_medium=partnership&utm_source=XFlow", status: 302 },
  /* BetterLinks */
  { src: "^/go/trustsync/?$", dest: "https://apps.shopify.com/customer-review-app", status: 302 },
  /* BetterLinks */
  { src: "^/Schedule-a-Call-Now/?$", dest: "https://storeware.io/storefaq-talk-with-expert/", status: 302 },
  /* legacy index.php permalinks */
  { src: "^/index\\.php(/.*)?$", dest: "$1", status: 301 },
  /* tag archives were never a destination */
  { src: "^/tag/.*", dest: "/blog/", status: 301 },
  /* A1 decision: single author, consolidate */
  { src: "^/author/.*", dest: "/blog/", status: 301 },
  /* gone, and saying so stops crawlers retrying */
  { src: "^/(wp-json|wp-admin|wp-includes)(/.*)?$", status: 410 },
  /* gone */
  { src: "^/xmlrpc\\.php$", status: 410 },
];
