// @ts-check
import { readFile, writeFile } from 'node:fs/promises';
import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import { platformRoutes } from './src/lib/redirects.ts';

/**
 * Guide §A2 / §B2. Generated by scripts/gen-redirects.mjs from the live URL
 * inventory — every path WordPress serves today either exists here or is in
 * that list.
 *
 * Written straight into the built Vercel routing table rather than through
 * Astro's `redirects`, and PREPENDED. Both parts matter:
 *
 *  - Astro's adapter emits slash-less patterns under trailingSlash 'always'
 *    (`^/some-post$`), and every real old WordPress URL ends in a slash — so
 *    the rule never matches the URL people actually have.
 *  - It also orders them after the 308 slash-normaliser, which rewrites the
 *    slash-less form to the slashed one first, so that misses too. Both forms
 *    404. These run first and accept the slash either way.
 *
 * With the Build Output API the emitted config.json IS the routing table, so
 * this is the one place the rules can be written AND read back — which is what
 * scripts/assert-redirects.mjs does.
 */
const platformRouting = {
  name: 'storefaq:platform-routes',
  hooks: {
    'astro:build:done': async () => {
      const path = new URL('./.vercel/output/config.json', import.meta.url);
      const config = JSON.parse(await readFile(path, 'utf8'));
      const extra = platformRoutes.map(({ src, dest, status }) =>
        dest ? { src, headers: { Location: dest }, status } : { src, status });
      config.routes = [...extra, ...(config.routes ?? [])];
      await writeFile(path, JSON.stringify(config, null, 2));
      console.log(`[platform-routes] prepended ${extra.length} routes to the Vercel config`);
    },
  },
};

export default defineConfig({
  site: 'https://storefaq.io',
  // Guide §A2: not optional. Every existing WP URL ends in a slash;
  // without this every backlink costs a 301 hop.
  trailingSlash: 'always',
  build: { format: 'directory' },
  output: 'static',
  adapter: vercel(),
  integrations: [
    mdx(),
    platformRouting,
    // Static routes only. Blog + categories are SSR and get their own
    // endpoint (guide §B5) so new posts appear without a rebuild.
    sitemap({
      filter: (page) => !/\/(blog|category)\//.test(page),
    }),
  ],
  vite: { plugins: [tailwindcss()] },
});
