// @ts-check
import { readFile, writeFile } from 'node:fs/promises';
import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import { existsSync } from 'node:fs';
import { platformRoutes } from './src/lib/redirects.ts';

/**
 * Where WordPress uploads live. The blog reads at request time, so a new
 * post's images cannot be mirrored at build time the way the docs' were —
 * they are served through /media/, the same URL space as the mirror: what
 * is on disk is served from disk, anything else is proxied from here. Not a
 * secret; defaults to the live site because that is where the content is.
 */
const WP_URL = (process.env.WP_URL ?? 'https://storefaq.io').replace(/\/$/, '');

/**
 * Guide §A2 / §B2. Generated by scripts/gen-redirects.mjs from the live URL
 * inventory — every path WordPress serves today either exists here or is in
 * that list.
 *
 * Written straight into the built Vercel routing table rather than through
 * Astro's `redirects`, and PREPENDED. Both parts matter:
 *
 *  - Astro's adapter emits slash-less patterns under trailingSlash 'always'
 *    (`^/some-post$`), and every real old WordPress URL ends in a slash — so
 *    the rule never matches the URL people actually have.
 *  - It also orders them after the 308 slash-normaliser, which rewrites the
 *    slash-less form to the slashed one first, so that misses too. Both forms
 *    404. These run first and accept the slash either way.
 *
 * With the Build Output API the emitted config.json IS the routing table, so
 * this is the one place the rules can be written AND read back — which is what
 * scripts/assert-redirects.mjs does.
 */
const platformRouting = {
  name: 'storefaq:platform-routes',
  hooks: {
    'astro:build:done': async () => {
      const path = new URL('./.vercel/output/config.json', import.meta.url);
      const config = JSON.parse(await readFile(path, 'utf8'));
      const extra = platformRoutes.map(({ src, dest, status }) =>
        dest ? { src, headers: { Location: dest }, status } : { src, status });
      /* The adapter emits its on-demand (non-ISR) routes slash-less —
       * `^/api/subscribe$` — under a trailingSlash 'always' config whose own
       * rule 308s every request TO the slashed form first. The slashed request
       * then matches nothing and falls to the 404 catch-all: every API
       * endpoint dead on deploy. Same defect as the redirects above, same
       * fix: accept the slash either way. scripts/assert-redirects.mjs walks
       * each such route through the table to prove it lands on a function. */
      const slashed = (config.routes ?? []).map((r) =>
        r.dest === '_render' && /[^/]\$$/.test(r.src) ? { ...r, src: r.src.replace(/\$$/, '/?$') } : r);
      const routes = [...extra, ...slashed];
      /* After `handle: filesystem`, so a mirrored file wins and only what is
       * missing goes to WordPress. Guide §B5's /wp-content proxy, under the
       * one path the output is allowed to contain. */
      const fs = routes.findIndex((r) => r.handle === 'filesystem');
      const proxy = { src: '^/media/(.*)$', dest: `${WP_URL}/wp-content/uploads/$1`,
        headers: { 'cache-control': 'public, max-age=31536000, immutable' } };
      routes.splice(fs < 0 ? routes.length : fs + 1, 0, proxy);
      config.routes = routes;
      await writeFile(path, JSON.stringify(config, null, 2));
      console.log(`[platform-routes] prepended ${extra.length} routes to the Vercel config, media proxy -> ${WP_URL}`);
    },
  },
};

export default defineConfig({
  site: 'https://storefaq.io',
  // Guide §A2: not optional. Every existing WP URL ends in a slash;
  // without this every backlink costs a 301 hop.
  trailingSlash: 'always',
  build: { format: 'directory' },
  output: 'static',
  adapter: vercel({
    /* Guide §B6: the on-demand routes (blog, categories, feed) are held at the
     * edge and purged by WordPress on publish through the bypass token — the
     * mu-plugin sends it. A day's expiry is the safety net if a purge is
     * missed; API routes are never cached. */
    isr: {
      expiration: 60 * 60 * 24,
      bypassToken: process.env.VERCEL_BYPASS_TOKEN,
      /* API routes, and the blog search: ISR keys on the path alone and drops
       * the query string, so ?s= must not be cached that way. */
      exclude: [/^\/api\//, /^\/blog\/search\/?$/],
    },
  }),
  integrations: [
    mdx(),
    platformRouting,
    // Static routes only. Blog + categories are SSR and get their own
    // endpoint (guide §B5) so new posts appear without a rebuild.
    sitemap({
      filter: (page) => !/\/(blog|category)\//.test(page),
      customSitemaps: ['https://storefaq.io/sitemap-blog.xml'],
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
    server: {
      proxy: {
        /* Dev only — the same rule the Vercel config gets above. */
        '/media': {
          target: WP_URL,
          changeOrigin: true,
          rewrite: (p) => p.replace(/^\/media\//, '/wp-content/uploads/'),
          bypass: (req) => existsSync(new URL('./public' + req.url.split('?')[0], import.meta.url)) ? req.url : undefined,
        },
      },
    },
  },
});
