// Pulls the privacy policy's prose out of the captured page into
// src/data/privacy.ts.
//
// Generated rather than transcribed: it is a legal document that has to be
// reproduced word for word, and the generator is also what enforces §B1 —
// every class and every builder wrapper is dropped here, so none can reach
// the output.
//
// Re-run against a fresh capture if the policy is amended.
import { readFileSync, writeFileSync } from 'node:fs';
import { parse } from 'node-html-parser';

const html = readFileSync('reference/html/privacy-policy.html', 'utf8');
const root = parse(html);
const content = root.querySelector('.entry-content');
if (!content) throw new Error('no .entry-content in the capture');

/** Block tags kept as blocks; everything else is unwrapped. */
const BLOCK = new Set(['P', 'H2', 'H3', 'H4', 'UL', 'OL', 'LI', 'BLOCKQUOTE']);
/** Inline tags kept; `strong` inside a heading is dropped as redundant — the
 *  heading carries the weight in CSS instead, so nothing changes on screen. */
const INLINE = new Set(['STRONG', 'EM', 'B', 'I', 'CODE', 'A', 'BR', 'SUP', 'SUB']);
/** The only attributes allowed through. `id` is kept so existing deep links
 *  into the policy keep working. */
const ATTRS = { A: ['href'], '*': ['id'] };

const esc = (s) => s.replace(/&(?!(?:[a-zA-Z]+|#\d+);)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const render = (node, inHeading = false) => {
  if (node.nodeType === 3) return esc(node.rawText);
  if (node.nodeType !== 1) return '';
  const tag = node.rawTagName?.toUpperCase();
  const kids = () => node.childNodes.map((n) => render(n, inHeading || /^H[1-6]$/.test(tag))).join('');
  if (tag === 'BR') return '<br />';
  if (tag === 'STRONG' && inHeading) return kids();          // redundant inside a heading
  if (!BLOCK.has(tag) && !INLINE.has(tag)) return kids();     // unwrap
  const attrs = [...(ATTRS[tag] ?? []), ...ATTRS['*']]
    .map((a) => [a, node.getAttribute(a)])
    .filter(([, v]) => v)
    .map(([a, v]) => ` ${a}="${v.replace(/"/g, '&quot;')}"`).join('');
  const t = tag.toLowerCase();
  return `<${t}${attrs}>${kids()}</${t}>`;
};

const body = content.childNodes.map((n) => render(n)).join('\n')
  .split('\n').map((l) => l.trim()).filter(Boolean).join('\n');

const bad = body.match(/class=|wp-|eb-|is-layout-/);
if (bad) throw new Error('WordPress markup survived: ' + bad[0]);

writeFileSync('src/data/privacy.ts', `/**
 * /privacy-policy/ — the policy prose.
 *
 * Generated by scripts/extract-privacy.mjs from the captured page: a legal
 * document has to be reproduced word for word, and generating it is also what
 * enforces §B1 — every class and wrapper is dropped at extraction time, so
 * none can reach the output.
 *
 * The heading ids are kept verbatim so existing deep links still resolve. Note
 * that the first one reads "data-collected-by-betterdocs" while its heading
 * says "Data Collected By StoreFAQ" — a leftover from the policy this one was
 * copied from. Changing it would break any link that already points at it.
 *
 * A redundant <strong> wrapping each heading's text is dropped; the headings
 * carry weight 700 from CSS instead, which is what the original renders.
 */
export const privacyHtml = ${JSON.stringify(body)};
`);
console.log(`${body.split('\n').length} blocks -> src/data/privacy.ts`);
console.log(body.split('\n').slice(0, 4).map((l) => '  ' + l.slice(0, 100)).join('\n'));
