/**
 * /changelog/ — the release timeline, newest first.
 *
 * Generated by scripts/scrape-changelog.mjs from the live page. Entry bodies
 * carry inline markup (<strong>, <em>, <a>, <code>, <br>) and nothing else:
 * every attribute and every wrapper the page builder added is dropped at
 * scrape time, so no WordPress class can reach the output (§B1).
 *
 * 33 entries, v3.7.2 (August 27, 2026) down to v1.0.0.
 */
export interface ChangelogSection {
  heading: string;
  /** Inline HTML — rendered with set:html. */
  items: string[];
}

export interface ChangelogEntry {
  date: string;
  version: string;
  sections: ChangelogSection[];
}

export const changelog: ChangelogEntry[] = [
  {
    date: 'August 27, 2026',
    version: 'v3.7.2',
    sections: [
      {
        heading: 'Improvements',
        items: [
          '<strong>Sidekick save results</strong> — changes made through Sidekick now confirm successfully after saving.',
          '<strong>Full FAQ content for Sidekick</strong> — get complete FAQ content in a single request for translations and rewrites.',
          '<strong>Multilingual AI Chatbot</strong> — replies now follow the customer’s language.',
          '<strong>Theme editor tracking</strong> — theme editor views are no longer counted as billable FAQ page views.',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed ask tab submission when questions are confirmed even when notification emails fail.',
          'Fixed instant Answer navigation when deep links now open and highlight the correct section.',
          'Fixed the Dashboard action now highlights the Live Chat card.',
          'Fixed Sidekick privacy — feedback submitter names are no longer returned.',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'August 20, 2026',
    version: 'v3.7.1',
    sections: [
      {
        heading: 'New Features',
        items: [
          '<strong>StoreFAQ in Shopify Sidekick</strong> — ask about your FAQs, settings, products, and plan in plain language.',
          'Added <strong>FAQ create and edit actions</strong>, <strong>translation support </strong> from Sidekick with direct access to the relevant FAQ.',
          'Added the <strong>StoreFAQ version</strong> to the Shopify admin footer.',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Improved FAQ search to match individual terms across FAQ questions, answers, and group names.',
          'Improved FAQ create and edit actions for better discoverability from Sidekick.',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed FAQ search returning no results when merchants used natural-language questions.',
          'Fixed empty FAQ groups being incorrectly reported as unavailable.',
          'Fixed intent values being incorrectly handled when opening the FAQ editor.',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'August 17, 2026',
    version: 'v3.7.0',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Improved Shopify token management and authentication reliability.',
          'Updated Shopify API to version <strong>2026-07</strong>.',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed expiring-token migration and retry handling.',
          'Fixed minor authentication-related issues.',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'August 10, 2026',
    version: 'v3.6.9',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Performance and maintenance updates',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'August 9, 2026',
    version: 'v3.6.8',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Newly created FAQ groups now stay at the top of the list',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed FAQ groups reshuffling when filtering the list',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'August 6, 2026',
    version: 'v3.6.7',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Dashboard app recommendations now update without an app update',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed usage charges missing from billing records',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'August 2, 2026',
    version: 'v3.6.6',
    sections: [
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'August 2, 2026',
    version: 'v3.6.5',
    sections: [
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed a crash when editing translated FAQ titles in the design editor',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'July 28, 2026',
    version: 'v3.6.4',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Dashboard app recommendation updates',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'July 28, 2026',
    version: 'v3.6.3',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Improved dashboard app recommendations display on mobile',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'July 27, 2026',
    version: 'v3.6.2',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Upgraded to Shopify’s latest API',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed the storefront FAQ page not showing the visitor’s selected language',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'July 14, 2026',
    version: 'v3.6.1',
    sections: [
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed Live Chat showing as inactive on the dashboard',
          'Fixed icon removal in Instant Answer design settings',
          'Fixed AI bot toggle showing the wrong state in the agent inbox',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'July 13, 2026',
    version: 'v3.6.0',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Rebuilt on Shopify’s latest app platform for better speed and reliability',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'June 22, 2026',
    version: 'v3.5.1',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Design menu revamp',
          'More accurate FAQ view analytics',
          'Message shortcuts improvements',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'June 17, 2026',
    version: 'v3.5.0',
    sections: [
      {
        heading: 'New Features',
        items: [
          '<strong>AI Chatbot</strong> for the Instant Answer widget',
          'Chatbot learns from your FAQs, products, pages, collections & blogs',
          'Auto-reply in Live Chat with human handover',
          'Custom chatbot instructions & content controls',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Sync History screen for chatbot content',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'June 8, 2026',
    version: 'v3.4.5',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Faster app navigation',
          'Smoother page loading',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'June 4, 2026',
    version: 'v3.4.4',
    sections: [
      {
        heading: 'New Features',
        items: [
          'Guided onboarding setup',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'App status cards on dashboard',
          'Mobile support for Live Chat',
          'AI Autowrite in FAQ editor',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'May 21, 2026',
    version: 'v3.4.3',
    sections: [
      {
        heading: 'New Features',
        items: [
          'Message Shortcuts for Live Chat',
          'Send chat transcript via email',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Auto-applied plan coupons at checkout',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Coupon checkout issue fixed',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'April 28, 2026',
    version: 'v3.4.2',
    sections: [
      {
        heading: 'New Features',
        items: [
          'File attachments in Live Chat',
          'Emoji picker in chat',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Better file upload error messages',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Chat window layout fixes',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'April 22, 2026',
    version: 'v3.4.1',
    sections: [
      {
        heading: 'New Features',
        items: [
          'Multi-language FAQ import & export',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Dashboard & FAQ performance boost',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'April 5, 2026',
    version: 'v3.4.0',
    sections: [
      {
        heading: 'New Features',
        items: [
          '<strong>Live Chat</strong>',
          'Chat management from Shopify admin',
          'Chat design customization',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Guest chat support',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'January 27, 2026',
    version: 'v3.3.0',
    sections: [
      {
        heading: 'New Features',
        items: [
          'StoreFAQ branding toggle',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Mobile FAQ display improvements',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed duplicate FAQ block design conflict',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'November 3 2025',
    version: 'v3.2.0',
    sections: [
      {
        heading: 'New Features & Improvements',
        items: [
          '<strong>Localization & Search</strong>',
          'Added <strong>multi-language support </strong>across the app',
          'Improved article search with search support in article queries',
          '<strong>Integrations & Billing</strong>',
          'Added FluentCRM integration with subscription event support',
          'Enabled usage-based charge activation via cron for automated billing',
        ],
      },
    ],
  },
  {
    date: 'September 23 2025',
    version: 'v3.1.0',
    sections: [
      {
        heading: 'New Features & Improvements',
        items: [
          '<strong>Subscription System</strong>',
          'Introduced a dedicated Subscription UI for managing plans',
          'Added subscription checkout flow',
          'Implemented flexible pricing plans',
          'Added coupon support for discounts during checkout',
        ],
      },
    ],
  },
  {
    date: 'June 22 2025',
    version: 'v3.0.0',
    sections: [
      {
        heading: 'New Features & Improvements',
        items: [
          '<strong>Instant Answer feature added for StoreFAQ app</strong>',
          'FAQ view form Instant Answer App',
          'Search FAQ from Instant Answer App',
          'Customise Instant Answer App',
          'Instant Answer initial Api caching',
          'All pages’ individual FAQ support added',
          'API version upgraded to the latest 2025-04',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'FAQ schema bug fix',
        ],
      },
    ],
  },
  {
    date: 'April 24, 2025',
    version: 'v2.1.2',
    sections: [
      {
        heading: 'New Features',
        items: [
          'FAQ schema',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'March 22, 2025',
    version: 'v2.1.1',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'User-interactions cards added',
          'Build for Shopify feedback',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Polaris CSS load issue',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'March 02, 2025',
    version: 'v2.1.0',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Build for Shopify feedbacks',
          'Settings page revamp',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Collection not showing in app block fixed',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'February 05, 2025',
    version: 'v2.0.1',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Replaced the custom color picker with Shopify’s Color Picker component',
          'Updated the Settings page by adding a Top Bar with Tabs, replacing the legacy sidebar',
          'Made the Design Editor responsive',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed spacing issues in the Settings page tabs',
          'Resolved form reset issues with the Contextual Save Bar',
        ],
      },
    ],
  },
  {
    date: 'January 27, 2025',
    version: 'v2.0.0',
    sections: [
      {
        heading: 'Upgrades & Updates',
        items: [
          'Upgraded Polaris to the latest version',
          'Updated Shopify API version',
          'Updated App Bridge to the latest version',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Migrated Shopify API integration from REST to GraphQL',
          'Redesigned the Design page to use App Bridge’s latest full-screen modal instead of a separate route',
          'Implemented Contextual Save Bar following Shopify’s latest guidelines',
          'Refactored and improved Import/Export functionalities',
          'Enhanced product search and autocomplete using Shopify’s APIs',
          'Added support to display FAQ Groups on individual collection pages',
          'Implemented multilingual slug generation',
          'Enabled scroll-to-active functionality for FAQ items',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Fixed incorrect date range display in dashboard statistics',
          'Resolved modal state issue after FAQ creation in the edit page',
          'Corrected FAQ list page filtering',
          'Fixed issues with FAQ group image deletion and updating',
        ],
      },
    ],
  },
  {
    date: 'November 06, 2024',
    version: 'v1.1.1',
    sections: [
      {
        heading: 'Improvements',
        items: [
          'Theme App Extension structural improvement',
        ],
      },
      {
        heading: 'Issues & Bug Fixes',
        items: [
          'Mobile Responsive and APP Block support',
          'Some minor bug fixes',
        ],
      },
    ],
  },
  {
    date: 'May 07, 2024',
    version: 'v1.1.0',
    sections: [
      {
        heading: 'Features',
        items: [
          'FAQ group drag & drop',
        ],
      },
      {
        heading: 'Improvements',
        items: [
          'Product search',
          'Ability to search and Select Product collection from FAQ Group edit',
          'Show specific FAQ group to Custom Product collection pages',
        ],
      },
      {
        heading: 'Upgrade',
        items: [
          'Shopify API version upgrade ~ <code>2024-04</code>',
          'Shopify Polaris version upgrade ~ <code>13.3.0</code>',
        ],
      },
    ],
  },
  {
    date: 'October 08, 2023',
    version: 'v1.0.0',
    sections: [
      {
        heading: 'Initial Beta Release',
        items: [

        ],
      },
    ],
  },
];
